apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-build-ci
spec:
  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
    volumeMounts:
    - name: m2
      mountPath: /root/.m2/
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "2.5Gi"
        cpu: "1"

  - name: docker-tools
    image: rmkanda/docker-tools:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run
      name: docker-sock
    - mountPath: /tmp/trivycache/
      name: trivycache
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "200m"

  - name: trufflehog
    image: rmkanda/trufflehog
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"

  - name: licensefinder
    image: licensefinder/license_finder
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "200m"

  volumes:
  - name: m2
    hostPath:
      path: /tmp/.m2/
  - name: docker-sock
    hostPath:
      path: /var/run
  - name: trivycache
    hostPath:
      path: /tmp/trivycache/
